get_filename_component(packagemanager_dir "${RCF_PATH}/intern/packages/" ABSOLUTE)

set(RCF_PACKAGES "" CACHE INTERNAL "")

function(rcf_addpackage packagename)
  set(package_version "newest")
  if(${ARGC} EQUAL 2)
    set(package_version ${ARGV1})
  endif()

  cmake_policy(PUSH)
  cmake_policy(SET CMP0057 NEW)
  if("${packagename}" IN_LIST RCF_PACKAGES)
    set(packagemanager_dir "${${packagename}_PACKAGE_DIR}")
  endif()
  cmake_policy(POP)

  set(package_file "")
  if(EXISTS "${packagemanager_dir}/${packagename}.cmake")
    message(STATUS "Looking for ${packagename} in the repo: found")
    set(package_file "${packagemanager_dir}/${packagename}.cmake")
    set(package_protocol "")
    set(package_source "")
    set(package_revision "")
    include("${packagemanager_dir}/${packagename}.cmake")    
  else()
    message("Looking for ${packagename} in the repo: not found")
  endif()
  
  if(NOT ${package_protocol} STREQUAL "")
    rcf_addlocation(${packagename}${package_version} ${package_protocol} ${package_source})
    if(NOT ${package_revision} STREQUAL "")
      rcf_obtain_project(${packagename}${package_version} outdir ${package_revision})      
    else()
      rcf_obtain_project(${packagename}${package_version} outdir)
    endif()

    build_package(${outdir})
  endif()
endfunction()

function(rcf_register_package name)
  set(RCF_PACKAGES "${RCF_PACKAGES};${name}" CACHE INTERNAL "")
  set(${name}_PACKAGE_DIR "${CMAKE_CURRENT_LIST_DIR}/packages" CACHE INTERNAL "")
endfunction()

function(rcf_register_package_repository name protocol source)
  rcf_obtain(${name} ${protocol} ${source} dir)
  if (EXISTS ${dir}/packagelist.cmake)
    include("${dir}/packagelist.cmake")
  endif()
endfunction()